#!/bin/bash

#!/bin/bash
start_time=$(date +%s)

for file in *.eqx; do
  echo "Running: $file"
  equinox $file || exit 1
  echo "Finished: $file"
done

end_time=$(date +%s)
elapsed=$((end_time - start_time))

echo "Time taken: $elapsed seconds"

